// src/components/search/search.svelte
<script lang="ts">
import type { ChangeEventHandler } from 'svelte/elements';

let client = $state<Pagefind>();
let query  = $state<string>('');
let result = $derived(client?.search(query));


function handler(): ChangeEventHandler<HTMLInputElement> {
  let debounce: number | undefined;

  return event => {
    clearTimeout(debounce);
    const value = event.currentTarget.value;
    const url = new URL(window.location.href);
    (value)
      ? url.searchParams.set('q', value)
      : url.searchParams.delete('q');
    debounce = setTimeout(() => window.history.pushState({}, '', url), 1000);
  }
}

function sync() {
  const params = new URLSearchParams(window.location.search);
  query = params.get('q') || '';
}

const require = (path: string) => import(/* @vite-ignore */path);

$effect(() => {
  sync();
  require('/pagefind/pagefind.js').then(pf => client = pf);
});
</script>


<svelte:window on:popstate={sync}/>

{#snippet tile(data: PagefindDocument)}
  <a class="c-search__result" href={data.url}>
    <header class="c-search__header">
      <h2 class="c-search__title">
        {data.meta.title}
      </h2>
    </header>
    <div class="c-search__excerpt">
      {@html data.excerpt}
    </div>
  </a>
{/snippet}

<article class="c-search">
  <h1>Search</h1>
  <input class="c-search__input" placeholder="Start typing here!"
    bind:value={query}
    on:input={handler()}/>

  {#if query && result}
    {#await result}
      Loading...
    {:then {results}}
      <section class="c-search__results">
        <div>Showing results for "{query}" ({results.length})</div>
        {#each results as page (page.id)}
          {#await page.data()}
            Loading...
          {:then page}
            {@render tile(page)}
          {/await}
        {/each}
      </section>
    {/await}
  {:else}
    <div>No results to show yet...</div>
  {/if}
</article>

// src/components/Search.tsx
import { createResource, createSignal, For, onMount } from "solid-js";


interface Pagefind {
  search: (query: string) => Promise<PagefindResponse>;
}

interface PagefindResult {
  id: string;
  data: () => Promise<PagefindDocument>;
}

interface PagefindResponse {
  results: PagefindResult[];
}

interface PagefindDocument {
  url: string;
  excerpt: string;
  filters: {
    author: string;
  };
  meta: {
    title: string;
    image: string;
  };
  content: string;
  word_count: number;
}


async function loadPagefind(): Promise<Pagefind> {
  const pf = "/_pagefind/pagefind.js";
  return await import(/* @vite-ignore */ pf);
}

function Result(props: { page: PagefindResult }) {
  const [data, setData] = createSignal<PagefindDocument>();

  onMount(async () => await props.page.data().then(setData))

  return (
    <>
      {data() && (
        <a class="c-search__result" href={data()!.url}>
          <header class="c-search__header">
            <h2 class="c-search__title">{data()!.meta.title}</h2>
            {/* <time class="c-search__date" datetime={dayjs().toISOString()}>{dayjs().format("MMM DD, YYYY")}</time> */}
          </header>
          <div class="c-search__excerpt" innerHTML={data()!.excerpt}></div>
        </a>
      ) || (
        <div>Loading...</div>
      )}
    </>
    
  )
}

const KEY = 'q' as const;
export default function Search() {
  const [query, setQuery] = createSignal('');

  // Search
  let pagefind: Pagefind;
  const [pages] = createResource(query, async (query: string) => await pagefind.search(query));

  // Update URL query and history
  let debounce: number;
  function syncHistory(value: string) {
    clearTimeout(debounce);
    debounce = setTimeout(() => {
      const url = new URL(window.location.href);
      (value) ? url.searchParams.set(KEY, value) : url.searchParams.delete(KEY);
      window.history.pushState({}, '', url);
    }, 1000);
  }

  // set query to URL param
  function sync() {
    clearTimeout(debounce);
    setQuery(new URLSearchParams(window.location.search).get('q') || '');
  }

  function onInput(value: string) {
    setQuery(value);
    syncHistory(value);
  }

  onMount(async () => {
    pagefind = await loadPagefind();
    sync();
    window.addEventListener('popstate', sync);
  });

  return (
    <article class="c-search">
      <h1>Search</h1>
      <input class="c-search__input" placeholder="Start typing here!"
        value={query()}
        onInput={e => onInput(e.target.value)}/>

      {query() && (
        <section class="c-search__results">
          <div>Showing results for "{query()}" ({pages()?.results.length || 0})</div>
          {pages() && <For each={pages()!.results}>{(page, i) => (
            <Result page={page} />
          )}</For>}
        </section>
      ) || (
        <div>No results to show yet...</div>
      )}
    </article>
  );
}
